### ISSUE TITLE
Robustness to camera type and which weights to use

### ISSUE THREAD

**Issue by rlee3359** [jingpeilu/CtRNet-robot-pose-estimation#1]
Hi! Fantastic work! Enjoyed reading your paper and was excited to see the code and give it a try with a Panda robot.

I've got the repo up and running on the test data. I just had some questions about the camera type and weights. There are 4 weights, one for each type of camera in the DREAM dataset. I understand these were trained on their specific camera dataset, but how robust is one set of weights to a different camera? Is it possible to train a model across multiple cameras to make it robust?

I ask since I would like to test this on my own real world set up, but I am using a different camera. Do you have any thoughts about how likely this is to work well with your pretrained weights, and can you suggest which weights to use?

I tried running the example image through all sets of provided weights, and while the output transform is relatively close, there are some small differences, and the keypoints for certain joints are in very different places, despite the rendered robot pose looking roughly the same, which seems strange. I was also surprised that the "orb" weights produced a different result from the "realsense" weights, despite them both using the same camera for data collection.

Looking forward to your response! Thanks for the great repository.

**Comment by jingpeilu** [comment]
Hi! Thank you for your interest in our work.

Since the network is trained by minimizing the difference of the rendered robot mask, camera parameter does matter. It is possible to use one set of weights for different cameras, but there can be small differences (which you have already observed). I would suggest using weights which the camera parameter is close to your setup.

As the keypoints are not directly supervised during the training, there can be factors that affect the appearance of the keypoints (e.g. camera parameter, PnP solver). The distribution of the collected dataset might also make difference.
